# NumPy

Numpy which stands for Numerical Python, is a library consisting of multidimensional array objects. Using NumPy, mathematical and logical operations on arrays can be performed.Tools like Pandas are built around the NumPy array.

We'll cover a few categories of basic array manipulations here:

In [1]:
import numpy as np

In [3]:
a = np.array([9,10,17,3]) # One-dimensional array
a

array([ 9, 10, 17,  3])

In [4]:

b = np.array([[3, 5, 2, 4], 
              [7, 6, 8, 8],
              [1, 6, 7, 7]])  # Two-dimensional array

c = np.array([[8, 1, 5, 9], 
              [8, 9, 4, 3],
              [0, 3, 5, 0]])  # Two-dimensional array
print(b)
print(c)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[8 1 5 9]
 [8 9 4 3]
 [0 3 5 0]]


## Arrays:
- Determining the size, shape of an array
- Indexing of arrays: Getting and setting the value of individual array elements
- Slicing of arrays: Getting and setting smaller subarrays within a larger array

In [5]:
print("Dimenssion of array a is : ", a.ndim)
print("Shape of array a is :", a.shape)
print("Size of array a is = ", a.size)

Dimenssion of array a is :  1
Shape of array a is : (4,)
Size of array a is =  4


In [6]:
print("Dimenssion of array b is : ", b.ndim)
print("Shape of array b is :", b.shape)
print("Size of array b is 3 * 4 = ", b.size)

Dimenssion of array b is :  2
Shape of array b is : (3, 4)
Size of array b is 3 * 4 =  12


### Operations on Numpy Array

In [8]:
c

array([[8, 1, 5, 9],
       [8, 9, 4, 3],
       [0, 3, 5, 0]])

In [7]:
#multiplying a constant with array
scalar =  c*3
print(scalar)

[[24  3 15 27]
 [24 27 12  9]
 [ 0  9 15  0]]


In [9]:
#adding b and c because they have same dimensions
add = b + c
print(add)

[[11  6  7 13]
 [15 15 12 11]
 [ 1  9 12  7]]


In [10]:
# element wise multipication
multiply = b*c 
print(multiply)

[[24  5 10 36]
 [56 54 32 24]
 [ 0 18 35  0]]


In [11]:
b

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [8]:
#taking square of every element in c
square = b**2
print(square)

[[ 9 25  4 16]
 [49 36 64 64]
 [ 1 36 49 49]]


In [12]:
b

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
c

array([[8, 1, 5, 9],
       [8, 9, 4, 3],
       [0, 3, 5, 0]])

In [9]:
#are elements of b > than c
logical= b > c
print(logical)

[[False  True False False]
 [False False  True  True]
 [ True  True  True  True]]


In [14]:
b

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
np.min(b)           # Minimum of the flattened array

1

In [16]:
np.min(b, axis=0)   # Minima along the first axis which means the minimum in first column,second column and so on.

array([1, 5, 2, 4])

In [17]:
np.min(b,axis = 1) # Minima along the second axis which means the minimum of first row,second row and so on.

array([2, 6, 1])

In [18]:
np.max(b)         # Maximum of the flattened array

8

### Array Indexing: Accessing Single Elements 

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [15]:
a

array([ 9, 10, 17,  3])

In [19]:
a[0]

9

In [20]:
a[-1]

3

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices

In [21]:
b

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [22]:
b[0, 0]

3

In [23]:
b[2, -1]

7

In [24]:
b[0, 0] = 12
b

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Creating copies of arrays


Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:

In [25]:
sub_copy = b.copy()
print(sub_copy)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [26]:
sub_copy[0, 0] = 42
print(sub_copy)

[[42  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a  3×3  grid, you can do the following

In [27]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation:

## Array Concatenation


All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

In [28]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [29]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [30]:
#for two-dimensional arrays:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [31]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# Thank you! 